# Generated by Django 5.2.1 on 2025-08-02 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_rg'),
        ('produtos', '0001_initial'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item_venda',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vendas',
            options={},
        ),
        migrations.RenameField(
            model_name='item_venda',
            old_name='preco_total',
            new_name='valor_total',
        ),
        migrations.RenameField(
            model_name='item_venda',
            old_name='preco_unitario',
            new_name='valor_unit',
        ),
        migrations.AlterField(
            model_name='item_venda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='item_venda',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='nome_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='total_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
