# Generated by Django 5.2.1 on 2025-07-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_escolaridade_cliente_profissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rg',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
